"""empty message

Revision ID: 62ac9935f6b9
Revises: 51b9e252a17b
Create Date: 2019-07-02 10:39:35.540275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ac9935f6b9'
down_revision = '51b9e252a17b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('construction_chaine_caractere_sur_liste_action_noeud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable_pattern', sa.String(), nullable=False),
    sa.Column('separateur', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['action_noeud.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('construction_chaine_caractere_sur_liste_action_noeud')
    # ### end Alembic commands ###
