"""empty message

Revision ID: 82be2befb858
Revises: caea6df95332
Create Date: 2019-10-04 10:57:44.399552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82be2befb858'
down_revision = 'caea6df95332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_noeud_execution', sa.Column('args_payload', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_noeud_execution', 'args_payload')
    # ### end Alembic commands ###
