"""empty message

Revision ID: c8ce4926f776
Revises: 62ac9935f6b9
Create Date: 2019-07-02 13:57:12.796140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ce4926f776'
down_revision = '62ac9935f6b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_evenement_action_noeud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisateur', sa.String(), nullable=False),
    sa.Column('participants', sa.String(), nullable=False),
    sa.Column('sujet', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lieu', sa.String(), nullable=False),
    sa.Column('date_heure_depart', sa.Text(), nullable=False),
    sa.Column('date_heure_fin', sa.Text(), nullable=False),
    sa.Column('est_maintenu', sa.Boolean(), nullable=False),
    sa.Column('hote_smtp', sa.String(), nullable=False),
    sa.Column('port_smtp', sa.String(), nullable=False),
    sa.Column('nom_utilisateur', sa.String(), nullable=False),
    sa.Column('mot_de_passe', sa.String(), nullable=False),
    sa.Column('enable_tls', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['action_noeud.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitation_evenement_action_noeud')
    # ### end Alembic commands ###
