"""empty message

Revision ID: eccb7efb059f
Revises: edf628a94c6d
Create Date: 2019-07-10 11:52:06.707806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eccb7efb059f'
down_revision = 'edf628a94c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date_recherche_interet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefixe', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['recherche_interet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('date_recherche_interet')
    # ### end Alembic commands ###
