"""empty message

Revision ID: edf628a94c6d
Revises: c8ce4926f776
Create Date: 2019-07-08 10:10:09.157207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf628a94c6d'
down_revision = 'c8ce4926f776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automate', sa.Column('notifiable', sa.Boolean(), nullable=False, server_default=sa.schema.DefaultClause("0")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('automate', 'notifiable')
    # ### end Alembic commands ###
